apiVersion: v1
kind: Service
metadata:
  name: wissamrh-web-service
spec:
  selector:
    app: wissamrh-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wissamrh-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wissamrh-web
  template:
    metadata:
      labels:
        app: wissamrh-web
    spec:
      containers:
      - name: wissamrh-container
        image: wissamrh/wissamrh:1.0.142
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: wissamrh-db-service
spec:
  selector:
    app: wissamrh-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP # Change to ClusterIP, as you don't need external access
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wissamrh-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wissamrh-db
  template:
    metadata:
      labels:
        app: wissamrh-db
    spec:
      containers:
      - name: mysql-container
        image: wissamrh/mysql:1.0.142
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: mydatabase
        - name: MYSQL_USER
          value: myuser
        - name: MYSQL_PASSWORD
          value: mypassword

---
apiVersion: v1
kind: Service
metadata:
  name: wissamrh-phpmyadmin-service
spec:
  selector:
    app: wissamrh-phpmyadmin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wissamrh-phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wissamrh-phpmyadmin
  template:
    metadata:
      labels:
        app: wissamrh-phpmyadmin
    spec:
      containers:
      - name: phpmyadmin-container
        image: wissamrh/php:1.0.142
        ports:
        - containerPort: 80
      env:
        - name: PMA_HOST
          value: wissamrh-db-service # Use the service name for MySQL
        - name: PMA_USER
          value: myuser
        - name: PMA_PASSWORD
          value: mypassword
