apiVersion: v1
kind: Service
metadata:
  name: wissamrh-web-service
spec:
  selector:
    app: wissamrh-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wissamrh-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wissamrh-web
  template:
    metadata:
      labels:
        app: wissamrh-web
    spec:
      containers:
      - name: wissamrh-container
        image: wissamrh/wissamrh:2.0.67
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: wissamha-db-service
spec:
  selector:
    app: wissamha-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP # Change to ClusterIP, as you don't need external access
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 10Gi  # Adjust the storage capacity as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Update with the appropriate storage class name
  hostPath:
    path: /var/lib/mysql  # Update with the appropriate host path


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Reference the previously defined PersistentVolume by name
  volumeName: mysql-pv

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wissamha-db-statefulset
spec:
  replicas: 1
  serviceName: wissam-db-service
  selector:
    matchLabels:
      app: wissamha-db
  template:
    metadata:
      labels:
        app: wissamha-db
    spec:
      containers:
      - name: mysql-container
        image: wissamrh/mysql:2.0.50
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: mydatabasewissam
        - name: MYSQL_USER
          value: myuser
        - name: MYSQL_PASSWORD
          value: mypassword
        volumeMounts:
        - name: database-volume
          mountPath: /var/lib/mysql  # Mount path within the container
  volumeClaimTemplates:
  - metadata:
      name: database-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: wissamrh-phpmyadmin-service
spec:
  selector:
    app: wissamrh-phpmyadmin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wissamrh-phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wissamrh-phpmyadmin
  template:
    metadata:
      labels:
        app: wissamrh-phpmyadmin
    spec:
      containers:
      - name: phpmyadmin-container
        image: wissamrh/php:2.0.34
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: wissamha-db-service # Use the service name for MySQL
        - name: PMA_USER
          value: myuser
        - name: PMA_PASSWORD
          value: mypassword
