# Use an official MySQL runtime as a parent image
FROM mysql:latest

# Set the MySQL root password
ENV MYSQL_ROOT_PASSWORD=root

# Create a database and user
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword

# When container starts, execute the following SQL script
COPY ./init.sql /docker-entrypoint-initdb.d/
