name: Build, Push, and Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: wissamrh/mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydatabase
          MYSQL_USER: myuser
          MYSQL_PASSWORD: mypassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set version as an environment variable
      run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV

    - name: Build App Docker image
      run: docker build -t wissamrh/wissamrh:${{ env.VERSION }} .

    - name: Build Database Docker image
      run: docker build -t wissamrh/mysql:${{ env.VERSION }} -f Dockerfile.database .

    - name: Build phpMyAdmin Docker image
      run: docker build -t wissamrh/php:${{ env.VERSION }} -f Dockerfile.phpmyadmin .

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push App Docker image
      run: docker push wissamrh/wissamrh:${{ env.VERSION }}

    - name: Push Database Docker image
      run: docker push wissamrh/mysql:${{ env.VERSION }}

    - name: Push phpMyAdmin Docker image
      run: docker push wissamrh/php:${{ env.VERSION }}
